### ISSUE TITLE
Installation does not work

### ISSUE THREAD

**Issue by MatthiasRimm** [LetsConstructIT/Grasshopper-TeklaDrawingLink#1]
Hello!

I have Rhino 7 and Tekla 2021. When I try to install any of the releases and drag them on the grasshopper canvas, then nothing happens. Nothing shows up in the libraries folder either.

**Comment by the-S-U-I-T** [comment]
Same happened for me on Rhino6 and TS2021.
Instead tried TS2023 and all went well.
My guess is that TS2021 version library file is mistakenly some other TS version file (think)

**Comment by olszewski-grzegorz** [comment]
You're right. I have not properly targeted to Tekla 2021.
It is fixed now, sorry for inconvenience. I have replaced previous .gha for TS2021:

https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/releases/tag/1.4.0
