### ISSUE TITLE
Objects from view (all objects) for multiple views

### ISSUE THREAD

**Issue by dandad36** [LetsConstructIT/Grasshopper-TeklaDrawingLink#12]
I'm using the Objects from view definition with getting all views in the drawing. The key list and the drawing objects doesn't match with each other. The number of drawings match the tree structure of the keys but not with the tree structure of the drawing objects.  
![image](https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/assets/41262390/b73bf4d3-2716-4b01-a306-a59589a01024)

The drawing objects seem to be organized by key but is missing a lot of items.
![image](https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/assets/41262390/7f4b002a-8e63-424b-aff2-8c31b9c799fc)

**Comment by olszewski-grzegorz** [comment]
You're right. _Objects from View_ component is not written to properly handle input of more than one view. It struggles with properly structuring the output tree.

I have to rewrite it to solve your case.  Will be back to this issue when it will be ready.
