### ISSUE TITLE
Related Object tree structure

### ISSUE THREAD

**Issue by dandad36** [LetsConstructIT/Grasshopper-TeklaDrawingLink#13]
The tree structure of the Related Object definition does not match the tree structure of the input
![image](https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/assets/41262390/a539f7f2-564c-4244-abdc-70b7264dcfab)

**Comment by olszewski-grzegorz** [comment]
Thanks for raising this issue. It seems that simple iteration is not enough to preserve tree structure.
I have to change the input type for this component. Now it accepts single input. To fulfill your request it has to be changed to the tree.
I will be back with the solution soon.

**Comment by olszewski-grzegorz** [comment]
Fixed in v.2.4.0:
https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/releases/tag/2.4.0
