### ISSUE TITLE
Feature request: Moving existing drawing object

### ISSUE THREAD

**Issue by dandad36** [LetsConstructIT/Grasshopper-TeklaDrawingLink#15]
Hi, I was looking for a way to move a lot of marks in view but I couldn't find a way. Will there be a feature to edit the placing location of existing drawing objects like marks, dimensions, text symbols?

**Comment by olszewski-grzegorz** [comment]
Good idea! I had already moving marks on my list waiting for release before summer (there will be a big update with loop support).
But making it more general ... could be hard. In the model the movement of objects in 3d space is clear. But in the drawing, there are nuances like moving normally vs moving with the hold shift key (the leader line case). Dimensions are a completely different problem, they are related to the perpendicular vector to the real dimension line.

Please write down a little more about your needs. What exactly would you like to achieve? It will make the development process much easier.

**Comment by dandad36** [comment]
I think the most annoying part with drawing is the mark position (both the text and the arrow location). We always need to move them to a better location. I was thinking it would be nice to edit these location with grasshopper to make it consistent (for example always keeping it away from the geometry at a certain distance). I think the location can be edited by moving and dragging with vector or changing the point coordination.

On a somewhat related note, a visual tool like point and polyline display is highly appreciated in the drawing space too. It would make it easier to see the location before we bake them into Tekla

**Comment by olszewski-grzegorz** [comment]
Hi! It took much longer than I expected, but it's live in the newest release (v.2.11.0):
https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/releases/tag/2.11.0

During the upcoming workshop I will present and share a script which utilizes those new components.
