### ISSUE TITLE
Name Parameter access

### ISSUE THREAD

**Issue by Darozas** [LetsConstructIT/Grasshopper-TeklaDrawingLink#16]
Hi All 

Thanks for your astonishing work!!! Well done.

Can you access these parameters ? 
![image](https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/assets/19796221/6e9ca513-9ebe-4343-8eb9-3a067117437d)

Regards

**Comment by olszewski-grzegorz** [comment]
Just to precise: you want to read / write / or both ? :)

**Comment by Darozas** [comment]
> Just to precise: you want to read / write / or both ? :)

Hi Both read and write.

Can you add Read for assembly position number as well?

![image](https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/assets/19796221/2ad40694-ab0c-459a-af2b-c8565aae759c)


Regards

**Comment by olszewski-grzegorz** [comment]
I have planned work for drawing properties - thanks for the good idea.

But the position can be obtained via:
- _Drawing Source_ from the Drawing Link
-  _Get Property_ from the Model link (property name: ASSEMBLY_POS)

**Comment by Darozas** [comment]
Ok thanks for clarification.

Do you have any time scale on implementing this new feature?

Regards

**Comment by Darozas** [comment]
Wow that was super fast Thanks.

On it to try !!!!

Thanks Again!!!!

**Comment by Darozas** [comment]
Verry nice thanks for your hard work !!!

![image](https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/assets/19796221/c5c6e1fc-cd7e-4b90-8b1a-db870cb0ad57)

**Comment by Darozas** [comment]
Well Done Keep it up!!!

**Comment by Darozas** [comment]
Hi 

I have found major bug.

When you use it it will wipe out all sheet layouts on all drawings.

Can you have a look at it please?

Regards

**Comment by olszewski-grzegorz** [comment]
@Darozas 
You're right :/ This bug is related to the behavior of Get All Drawings. I checked only the scenario for selected ones, which is a little different.
Fixed version:
https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/releases/tag/2.5.1

Sorry for the inconvenience.
