### ISSUE TITLE
Text Alignment

### ISSUE THREAD

**Issue by M4rin3s** [LetsConstructIT/Grasshopper-TeklaDrawingLink#17]
Hi,
first of all, amazing job with this TeklaDrawing Link! This is an absolute game changer.
I have an issue with text right alignment. I can't find any way to input this kind of parameter, but in the output there is a default value Alignment: Left. Is is possible to change alignment with your plugin? 
![image](https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/assets/161320322/b48bc974-62c1-4a75-9daf-7fddc7e88e82)

**Comment by olszewski-grzegorz** [comment]
Hi! There are two different approaches to this task:
1) Expose Alignment property (left/center/right) in the Text Attributes - it will be only used for the multiline texts (cases when UseWortWrapping = true and the RulerWidth is small enough to wrap the text). The text still will be located as a center around the provided point.
2) Create a new component to truly align the text to a point. Then you will be able to position text to the top-left / bottom-right / etc. 

How would you like to treat your case?

**Comment by M4rin3s** [comment]
I would like to use word wrapping, but I also can't find any boolean operator for turning on Word wrapping in Text Attributes (TATR).

**Comment by olszewski-grzegorz** [comment]
Ok, that sounds clear. I don't promise too much but will try to deliver this improvement by the beginning of week 10.

**Comment by M4rin3s** [comment]
> Ok, that sounds clear. I don't promise too much but will try to deliver this improvement by the beginning of week 10.

Looking forward to hearing good news :)

**Comment by olszewski-grzegorz** [comment]
Please check the newest version with updated Text Attributes component:
https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/releases/tag/2.6.0

**Comment by M4rin3s** [comment]
Great news! Thank you for super fast adding this new feature to the plugin.
Dobra robota 🫡
