### ISSUE TITLE
Rotate view

### ISSUE THREAD

**Issue by dandad36** [LetsConstructIT/Grasshopper-TeklaDrawingLink#18]
Hi there. I would like to request a feature for rotating view in drawing. I would like to rotate the view so certain elements in view is horizontal

**Comment by olszewski-grzegorz** [comment]
Please check the newest version with the Rotate View component:
https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/releases/tag/2.6.0

**Comment by dandad36** [comment]
Thank you for the great work 👍
