### ISSUE TITLE
Drawing Properties 

### ISSUE THREAD

**Issue by Darozas** [LetsConstructIT/Grasshopper-TeklaDrawingLink#19]
Hi Me again.

Is there a way to modify these fields ?

Regards

![image](https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/assets/19796221/819ecae9-a102-444e-a6d8-9cd4a9d93750)

**Comment by olszewski-grzegorz** [comment]
Feel free to submit any ideas :)

For that particular one, you should look into macros. Unfortunately, Tekla Drawing API does not cover all of those settings.
After recording the needed macro in Tekla you can invoke it from the GH with the _Run Macro_ component help.

I don't plan any development toward those settings. Without full support from Tekla for filtering and advanced level settings it does not make sense.
