### ISSUE TITLE
View label extract

### ISSUE THREAD

**Issue by dandad36** [LetsConstructIT/Grasshopper-TeklaDrawingLink#20]
I was trying to use the view type and view name to extract all the similar views from different drawings. I realized that the name in GH doesn't match with what I have in the drawing space. I think it was the original name from when it was created and became its internal name. It's hard to tell which view is which with this type of name, so I would like to request a way to extract the view label value of the current view.  
![image](https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/assets/41262390/e23fbe52-94d8-4e4a-ac46-f2a6b475c6a0)
![image](https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/assets/41262390/cc21977d-990e-4a26-aa07-f7bc2a3c10d6)

**Comment by olszewski-grzegorz** [comment]
Hi @dandad36 ! I get your point. There is a way to read the content of those tags so I will enhance this component in the next release. Thank you for the good idea :)

**Comment by olszewski-grzegorz** [comment]
Added in version 2.7.0:
https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/releases/tag/2.7.0
