### ISSUE TITLE
Wrong view frame rotation in different drawings

### ISSUE THREAD

**Issue by dandad36** [LetsConstructIT/Grasshopper-TeklaDrawingLink#22]
I'm filtering all the views from different drawings of the same view type (for example TopView) and the view and drawings frame geometries are extracted. However, the orientation of the view frame looks wrong. The definition use the same rotation as that of the current drawing (see pictures). I've tried it for different view types and models and still the same behavior so I think this is a bug
![image](https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/assets/41262390/2da8d734-4108-463a-8937-ec08b112ded9)
![image](https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/assets/41262390/1b316187-c970-4dbb-a4a4-8414cd5b997a)
![image](https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/assets/41262390/895a7e23-ad35-4e0d-9aa0-4091e7d5ded9)
![image](https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/assets/41262390/f34af4c4-58a5-45a9-b82a-c0e3f6c7e0f0)
![image](https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/assets/41262390/99d60499-86f5-417d-8771-2430bc4ea128)

**Comment by olszewski-grzegorz** [comment]
Hi! This issue is a consequence of the single-active-drawing policy in Tekla. This is a limitation that we have to learn to live with. You can operate on a single drawing at a time.

You should iterate over the drawings with the for loop. [Anemone ](https://www.food4rhino.com/en/app/anemone)could help. In the next big release (10th April) there will be in-build loop components in the Drawing Link.

**Comment by olszewski-grzegorz** [comment]
ps. I have added to the development list getting rectangles directly from the Drawing Size and View Frame Geometry components.  When I saw it on your screenshot then it hit me :)

**Comment by dandad36** [comment]
Thank you for the answer. I tested it with Anemone and it worked. Can't wait to see the big release :D
A comment about the drawing size and frame geometry when you are creating it, the unit of the rhino space and Tekla drawing space must be the same for the correct shape
