### ISSUE TITLE
Single-part drawings creation

### ISSUE THREAD

**Issue by Adam-Bednarek** [LetsConstructIT/Grasshopper-TeklaDrawingLink#23]
Hi Grzegorz!

Is there any way to create single-part drawings using your Drawing Link? I cannot find such component. If there's any walkaround that problem, please let me know, if not - that would be useful to implement in the future :)

Best regards,
Adam Bednarek

**Comment by olszewski-grzegorz** [comment]
Version 2.8.0 should handle with this:
https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/releases/tag/2.8.0

**Comment by Adam-Bednarek** [comment]
Whoa, that looks like a huge update!! Cannot wait to test it out!
