### ISSUE TITLE
Rebar dimension mark

### ISSUE THREAD

**Issue by KKdavidKK** [LetsConstructIT/Grasshopper-TeklaDrawingLink#24]
Hi grzegorz! First of all I want to thank you for the extraordinary work you are doing. Then I would like to ask you if there is a way to insert dimension marks for reinforcement bars in the drawings or if you plan to implement this functionality. I would also like to ask you if there is a way to filter the reinforcement bars by position number. For example, if I had several groups of reinforcement bars and wanted to create a dimension mark only for reinforcement bars with position numbers starting with "V", is it possible to do this?
Thank you!

**Comment by olszewski-grzegorz** [comment]
Hi! Simplest way to achieve:
![image](https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/assets/24588349/f4d57441-7297-4f4c-a862-d75eddf0648e)

Workflow:
- get all objects from view (or cast unit, depending on use case)
- filter drawing objects to Single Rebars / Reinforcement Group
- convert drawing to model objects
- query model objects with some report property
- filter model objects based on report values
- insert rebar mark

**Comment by KKdavidKK** [comment]
Thank you for the quick and detailed answer on how to filter rebar!
Sorry, but about the marks maybe I explained myself wrong. I meant not the usual marks but dimension marks like the ones surrounded in green in the pictures below. I wanted to ask you if there is any way to create them.

Thanks again!
![Rebar dimension mark_1](https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/assets/164378638/296bd2ac-96e3-416f-884d-826028a097a7)
![Rebar dimension mark_2](https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/assets/164378638/778beafc-b201-4455-88ce-c928383bae76)

**Comment by olszewski-grzegorz** [comment]
Ah, I get it. Unfortunately, Tekla Drawing API does not offer those capabilities. Standard workaround is to:
- filter out needed drawing objects
- use _Select Object_ GH component (it will mimic your behaviour in selecting drawing object entities)
- trigger macro which will do the rest (_Run Macro_ component)

You have to record macro once, from the Tekla Applications & components side pane.
