### ISSUE TITLE
Rebar group visible line and location

### ISSUE THREAD

**Issue by dandad36** [LetsConstructIT/Grasshopper-TeklaDrawingLink#25]
Hi amazing updates so far. I have a request to extract rebar group visible lines from drawing and then be able to modify its location if the visibility mode is customized. It's very time-consuming move the line for each group.
![image](https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/assets/41262390/4a617838-9b0a-4c93-a8d4-820371d10797)

**Comment by olszewski-grzegorz** [comment]
Very good idea @dandad36 ! I was a little worried that this setting wasn't available in Tekla Open API, but it looks like I was wrong :)

I will try to add it to the next release.

**Comment by olszewski-grzegorz** [comment]
Added in [v.2.10.0](https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/releases/tag/2.10.0)

This input accepts float values from 0.0 to 1.0. Their representation is the relative distance from the first rebar in the group.

![image](https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/assets/24588349/6f80b64c-1587-4204-9582-a80544e25274)

**Comment by dandad36** [comment]
Thank you it works well :)

**Comment by olszewski-grzegorz** [comment]
Hi @TrungVuDuy! Please, next time open new issue :)
There isn't ready-to-use solution.
For your need, I think you should combine reinforcement custom position from the drawing object with rebar geometries from the model object.
As far as I know, reinforcement custom position is measured from the first rebar toward the last, so if you grab all of them, measure relative length between, and then multiply it by drawing's rebar custom position, then you will obtain vector needed to move geometry of the first rebar from model to match it's curent drawing representation.
Something like this:

![image](https://github.com/user-attachments/assets/8f3d3372-ac2e-49b6-a227-978d83499ac4)
![image](https://github.com/user-attachments/assets/8791602c-8f3e-4198-a864-2724510e44da)

**Comment by TrungVuDuy** [comment]
Thanks a lot, @olszewski-grzegorz 
This method works well for normal groups. For tapered and curved groups we might need to construct a domain based on bar ranges.
