### ISSUE TITLE
DimLine creation

### ISSUE THREAD

**Issue by Mantsi** [LetsConstructIT/Grasshopper-TeklaDrawingLink#26]
Hi

I was following your youtube tutorial Dimensioning part I. I inserted all the three needed inputs but my component keeps adding two dimension lines for some reason. I had to add python command to delete the second one. The Dim component seems very simple as it self but I don't understand why it keeps adding the duplicate dimension line. 

Does anyone happen to understand the reasoning behind this.

The component receives 1 view,  2 points and 1 line.

![image](https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/assets/165034583/0ec5cc18-d0e0-4d1b-ba89-474c2f964ccc)

Thanks for the updates by the way. Great work and amazing tool that I have already made great progress with in my project.

**Comment by olszewski-grzegorz** [comment]
@Mantsi, you're right - thank you for raising this issue.

It seems in v.2.9.0 I have introduced a bug. Will try to fix it ASAP.

**Comment by olszewski-grzegorz** [comment]
New version (2.9.1) is live. Sorry for inconvenience :/

I had to change the way of insertion drawing annotations to handle multi-view scenarios. I hope it was the last so big change.

**Comment by olszewski-grzegorz** [comment]
Hi, I'm not sure that you will receive this message - please add any
issues/comments directly on GitHub.

The previous fix is still valid, I have not changed that part of the
codebase. For your previous case it still creates just one dimension line:
[image: image.png]

czw., 18 kwi 2024 o 14:52 Mantsi ***@***.***> napisał(a):
