### ISSUE TITLE
Curved section view

### ISSUE THREAD

**Issue by Karbofo7** [LetsConstructIT/Grasshopper-TeklaDrawingLink#28]
Hello!
Please tell me, can you add a "Curved section view" component to Grasshopper-TeklaDrawingLink in the future? It is very important for me

Do you think it is possible to create a component that would make a cut along a curve in Tekla? That is, not in an arc, as Curved section view does. I mean a cut along a complex curve, when the curve consists of many arcs and straight sections

**Comment by olszewski-grzegorz** [comment]
Hi! Welcome to the community :)

I have added Curved section view to the newest release (v.2.11.0):
https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/releases/tag/2.11.0

For your question about complex section view - I don't see such possibility. You can turn on the crazy mode and create with the Drawing Link set of different sections which will be located like it is the continuous curve, but ... there will be problems at the discontuinity nodes. Some elements will be visible in depth up/ down.

It's a request rather for Trimble - I'm just creating a wrapper around Tekla.

**Comment by Karbofo7** [comment]
> Я добавил вид изогнутого сечения в новейшую версию (v.2.11.0):

Thank you!
