### ISSUE TITLE
View Attributes Section View

### ISSUE THREAD

**Issue by M4rin3s** [LetsConstructIT/Grasshopper-TeklaDrawingLink#30]
Hi,
My issue apears when I try to create section views using **Section View** component from Model View (In this case Top View). 
When i set view properties input for _Attributes Name_ in **Model View (MV)** component it overrides my _View Attributes (VA)_ input in *Section View** component.

I can't set different _Detailed object level settings_ for my section views becasue View Properties template is taken from my Top View.

![image](https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/assets/161320322/1f7fff1b-14ad-4d2c-a3d1-308358344499)
![image](https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/assets/161320322/0f7dc97a-91b1-4abc-b373-1844623ceb86)

**Comment by olszewski-grzegorz** [comment]
Hello!
If you are talking about wrongly assigned Detailed object level settings or Filters then you have encountered serious limitations in the Tekla Open API. It's there from the beginning, and the only real solution to overcome those problems is to use macro (mimic user-interactions) at some point.

Every drawing view creation component has the right-click menu, where you can choose _Use macro_:
![image](https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/assets/24588349/88abfd75-0c0d-4cfd-af01-12c7d5178f75)
It will drastically increase the time needed for the view creation. The view will be inserted with the API, then it will be selected and the user interface with its properties will be displayed, correct settings will be loaded and the view will be modifided exactly the same way as you, as a user would do. Long way, but unfortunately, only to achieve correct effect when you are using filters and detailed object level settings.

Depending on the use-case, you can trigger correct macro later, when you have multiple views which should be modified with the same attributes. It will save some time, but still - macroing is time-consuming part of Tekla Drawing Open API, which I'm only wrapping in the Grasshopper.

**Comment by M4rin3s** [comment]
Thank's a lot for the response ;)
