### ISSUE TITLE
CU View attributes not recognized

### ISSUE THREAD

**Issue by andrisabla** [LetsConstructIT/Grasshopper-TeklaDrawingLink#31]
Thanks Greg for your work and great plugins 
New work era have began :)

![image](https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/assets/129769915/d44545fc-2749-409c-9c65-58b7581b4a34)
I am testing generating CU view with preset settings, but grasshopper anyway return view with wrong settings.
Preset settings in green and how the view should look if I generate it in Tekla drawing mode. 
Can you check please what could be an issue?

**Comment by olszewski-grzegorz** [comment]
Good to hear :)

Please, check below link, because I'm pretty sure that this is about of object level settings which you have in these preset:
https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/issues/30#issuecomment-2054126548

**Comment by andrisabla** [comment]
Thanks Grzegorz 
I didnt see closed issue list before )
