### ISSUE TITLE
Drawing object parameter bug

### ISSUE THREAD

**Issue by M4rin3s** [LetsConstructIT/Grasshopper-TeklaDrawingLink#35]
Hi,
there is some bug with drawing object parameter. I couldn't select it with multiple selection but right now I can't even select/move or delete this component. 

https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/assets/161320322/4bbda6b8-d50c-45dc-92ff-d41e88f83741

**Comment by M4rin3s** [comment]
Updated to newest release and it is the same from the beginning. But somehow it worked previously. 


https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/assets/161320322/3a92c79f-f6f1-4f53-a901-39f8b1ec6270

**Comment by M4rin3s** [comment]
I refreshed couple of times both Tekla and Grasshopper, and now it's working.

**Comment by olszewski-grzegorz** [comment]
Hi, I was able to recreate this issue when I turned off Tekla after the initialization of Rhino.
The current behavior is wrong, Model Link handle that situation in better way (still, it won't work as the connection Rhino-Tekla is initialized with the first opened Tekla instance).

Will try to enable moving/removing params from Drawing scope in that scenario. Thanks for raising this issue!

**Comment by olszewski-grzegorz** [comment]
Addressed in 2.12.1 (component can be moved, but the broken connection will not return):
https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/releases/tag/2.12.1
