### ISSUE TITLE
Modify View

### ISSUE THREAD

**Issue by duchoabn** [LetsConstructIT/Grasshopper-TeklaDrawingLink#36]
Hi Greg,
Please add component to control and modify View Attributes in Drawing
In your View Tab I see View Properites
How we can get all Tags attributes and can not modify the view attributes
Thanks
![image](https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/assets/23393253/3ac9e2b8-1b5a-4148-9c0d-858f2fbdffd0)

**Comment by olszewski-grzegorz** [comment]
Hi @duchoabn, welcome to GitHub!
For getting tag contents you can use _View properties_ component. Its last output is a list of view tags (A1, A2, ... A5).

Modification of the existin view attributes is currently not possible. You can bypass this limitation with recorded macro.
I will add your request to the roadmap with planned features.

**Comment by olszewski-grzegorz** [comment]
Modify view available since version 2.14.0
