### ISSUE TITLE
FindVisibleEdges throws object null exception.

### ISSUE THREAD

**Issue by Gintarich** [LetsConstructIT/Grasshopper-TeklaDrawingLink#39]
When using this component in Rhino 8, it throws an exception and doesnt work. 

I built the project from source and the problem seems to be at [line nr. 23](https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/blob/000e528f7a1bed16733248b2d3e90d6cf023e105/src/GrasshopperTeklaDrawingLink/Components/Geometries/FindVisibleEdgesComponent.cs#L23) in FindVisibleEdgesComponent.cs. 
"curve.Simplify()" method returns null curve, which causes an exception.
If i remove the line the component works fine, but probably more permanent solution is needed. 
Maybe something like
```csharp
Curve tempCurve =  curve.Simplify(CurveSimplifyOptions.All, RhinoDoc.ActiveDoc.ModelAbsoluteTolerance, RhinoDoc.ActiveDoc.ModelAngleToleranceRadians);
if(!tempCurve is null) curve = tempCurve;
```

**Comment by olszewski-grzegorz** [comment]
Hi @Gintarich!
Thanks for raising issue. I'm impressed you even point where fix should be applied :)
Fixed in 2.13.1:
https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/releases/tag/2.13.1
