### ISSUE TITLE
No Issues - Looking for an Update! 

### ISSUE THREAD

**Issue by fhernandez0303** [LetsConstructIT/Grasshopper-TeklaDrawingLink#42]
Just wanted to commend you for the hard work in putting these GH components together for the community. I've personally, made great use of them to automate many of my tasks. 

Thank you for the hard work! Is there anything in store for this work? I know that you've been working with Trimble Connect's API.

**Comment by TautvydasBakas** [comment]
Thanks for the update, Grzegorz! I'm really looking forward to testing out the Grasshopper Component inside of Tekla :)

**Comment by OskarScherdin** [comment]
Awesome work @olszewski-grzegorz , excited to try out the Rhino.Inside.Tekla version when that comes. You have done an amazing job so far.
