### ISSUE TITLE
Hide objects on View

### ISSUE THREAD

**Issue by ArthurKo33** [LetsConstructIT/Grasshopper-TeklaDrawingLink#44]
Hi Greg. Thank you for your work on tekla drawing link. Its amazing.
I want to make scripts that run on selected drawing and hides specified parts from views.
How can i do the function Hide object from View/Drawing.

**Comment by olszewski-grzegorz** [comment]
Welcome @ArthurKo33 !
If you want to use same workflow as a user, then you should try with a macro. Preselect needed objects with _Select Object_ component with and use the _Run Macro_ with registered macro content.

Another way would be to fake hidden objects by changing their appearance, to invisible line color.

If it is not enough for you, then I have to add new feature request to do it from the API level. It seems there is a class:
https://developer.tekla.com/doc/tekla-structures/2024/hideable-class-23747 which should help.
Please describe your need - it will help me in the component development.

**Comment by ArthurKo33** [comment]
Hi, Thanks for fast reply. Ocassionaly we need to make changes to Ga drawings. Sometimes becuase human mistake and sometime it just client request. The need to hide aluminium facade, cast plates and so on. Most of times the Ga drawings is heavy, and the time to make it manually is just to much. And it seems that drawing link can answer this need.

**Comment by olszewski-grzegorz** [comment]
Ok, I understand your need. I won't start development before release of the newest version, but I hope in October release there will be something for you :)

**Comment by ArthurKo33** [comment]
Thanks alot for your help.

**Comment by olszewski-grzegorz** [comment]
@ArthurKo33 added in 2.15.0:
https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/releases/tag/2.15.0

**Comment by ArthurKo33** [comment]
thanx
