### ISSUE TITLE
Different sizes from Tekla

### ISSUE THREAD

**Issue by Karbofo7** [LetsConstructIT/Grasshopper-TeklaDrawingLink#47]
Hi! 
This is a very good set of commands for Grasshopper. 
Tell me please: do you plan to add a Curved dimension (orthogonal reference lines), Curved dimension (radial reference lines), Radial dimension and others dimensions in the future?

**Comment by olszewski-grzegorz** [comment]
Hi @Karbofo7,
in the newest [version](https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/releases/tag/2.14.0) , there are two new dimension types: radial and curved.

I have to check before the next release if there is anything more missing in that area.

**Comment by Karbofo7** [comment]
> Привет@Karbofo7, в новейшей [версии](https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/releases/tag/2.14.0) , есть два новых типа размеров: радиальный и изогнутый. Вы их пробовали?
> 
> Мне нужно будет проверить перед следующим релизом, не упущено ли что-то еще в этой области.

I haven't had time to check it for a long time. But now I checked it: it seems to work well. Thank you!

**Comment by Karbofo7** [comment]
> Привет@Karbofo7 В новейшей версии есть [два](https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/releases/tag/2.14.0) новых типа размеров: радиальный и изогнутый. Вы их пробовали?
> 
> Мне нужно будет проверить перед следующим релизом, не упущено ли что-то еще в этой области.

I haven't had time to check it for a long time. But now I checked it: it seems to work well. Thank you!
