### ISSUE TITLE
Grasshopper Application | Stay on Top

### ISSUE THREAD

**Issue by fhernandez0303** [LetsConstructIT/Grasshopper-TeklaDrawingLink#48]
Hello Grzegorz, 

One issue I've come upon is just a UI issue. It would be great if your application can - _Stay on top_. Running the application has not been a problem, but it is hectic trying to always make it come back into the window.

**Comment by olszewski-grzegorz** [comment]
@fhernandez0303 , you are right, it will be added as an option in the next release. Thanks for suggestion!

I will wait for more voices/issues about the tool before releasing. I plan to do that in the mid of October.
Until that you can use the [PowerToys](https://learn.microsoft.com/pl-pl/windows/powertoys/always-on-top). Just as a temporary hack.

**Comment by olszewski-grzegorz** [comment]
@fhernandez0303 , I have mimicked same behavior as Tekla plugins. Grasshopper Application will stay on top main Tekla window.

Please give it a try in ver. 1.1:
https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/releases/tag/GA_1.1

**Comment by fhernandez0303** [comment]
Thank you, @olszewski-grzegorz .
