### ISSUE TITLE
About bake to tekla

### ISSUE THREAD

**Issue by better319** [LetsConstructIT/Grasshopper-TeklaDrawingLink#5]
the official version， bake to tekla by right click。

i found your new version used this

if it's possible to create the single Battery

,so that we can create the conpenment automatic by change value。

without right click

**Comment by olszewski-grzegorz** [comment]
Hi, thanks for reaching out!
Just for clarification: you would like to have the possibility to turn on _the automatic baking_? So the Tekla results persisted at the creation moment?
I must check if such a checkbox can be added to the GH top menu. If not, then some settings window will be needed.

**Comment by better319** [comment]
yes，Tekla results persisted at the creation moment。

there are a mouse right click menu item(about bake to tekla) in official gh plugin.  in the  batteryof create beam.

maybe there will be something error when i create some thing,but  use this ,i can choice the line or something one by one.so that i can see if it's wrong or right when objects create.

**Comment by better319** [comment]
> yes，Tekla results persisted at the creation moment。
> 
> there are a mouse right click menu item(about bake to tekla) in official gh plugin. in the batteryof create beam.
> 
> maybe there will be something error when i create some thing,but use this ,i can choice the line or something one by one.so that i can see if it's wrong or right when objects create.

yes，Tekla results persisted at the creation moment。

there are a mouse right click menu item(about bake to tekla) in official gh plugin. in the batteryof create beam.

maybe there will be something error when i create some thing,but use this ,i can choice the line or something one by one.so that i can see if it's wrong or right when objects create.
