### ISSUE TITLE
Reinforcement Properties | Rebar set

### ISSUE THREAD

**Issue by TrungVuDuy** [LetsConstructIT/Grasshopper-TeklaDrawingLink#51]
The "Reinforcement Properties" does not work with RebarSet. Is it a bug or a limitation?
![image](https://github.com/user-attachments/assets/00d1b7c8-4109-4b73-b35f-4b113723e28a)

**Comment by olszewski-grzegorz** [comment]
Limitation I would say. Rebar sets are not inheriting from typical Reinforcement class in Tekla Open API. They are much bigger than Reinforcement, as can be seen in documentation:
https://developer.tekla.com/doc/tekla-structures/2024/rebar-set-class-28429

But there is a property named RebarProperties which holds almost everything for the purpose of this Grasshopper component. I will try to add support for that in the next release (end of October).

**Comment by olszewski-grzegorz** [comment]
@TrungVuDuy added in 2.15.0
https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/releases/tag/2.15.0

**Comment by TrungVuDuy** [comment]
It works, thanks a lot @olszewski-grzegorz
