### ISSUE TITLE
Grasshopper Application won't start if I installed Rhino 8

### ISSUE THREAD

**Issue by Karbofo7** [LetsConstructIT/Grasshopper-TeklaDrawingLink#55]
When launching Grasshopper Application 1.1 it tries to launch Rhino 7, but I only have Rhino 8. What am I doing wrong? The latest update says that this error is fixed. But for some reason I still have this error.
![image_2024-10-21_16-03-04](https://github.com/user-attachments/assets/7755befb-191c-4bdd-82bf-5912ab6de734)

**Comment by olszewski-grzegorz** [comment]
@Karbofo7, sorry for inconvenience. I returned to that case but now with complete uninstalling Rhino 7.

You're right, the bug is still there, I have to fix it.

As a temporary workaround (if you would like of course) you could manipulate with settings. It will work only with Tekla <= 2023.

In the installation directory:
C:\TeklaStructures\2023.0\Environments\common\extensions\GrasshopperApplication

![image](https://github.com/user-attachments/assets/9689ba57-57ae-4301-9bd3-816331ad67b7)

After removing initial .config file and restoring the default one, you have to open file Grasshopper Application.exe.config with notepad and change there Rhino version to 8:
![image](https://github.com/user-attachments/assets/cf67ba2b-e3d1-4ab7-b8ef-9bffce66a254)

I will release the new version at the end of the week.

**Comment by Karbofo7** [comment]
> @Karbofo7, извините за неудобства. Я вернулся к этому делу, но теперь уже с полным удалением Rhino 7.
> 
> Вы правы, ошибка все еще есть, мне нужно ее исправить.
> 
> В качестве временного решения (если вы, конечно, этого хотите) вы можете манипулировать настройками. Это будет работать только с Tekla <= 2023.
> 
> В каталоге установки: C:\TeklaStructures\2023.0\Environments\common\extensions\GrasshopperApplication
> 
> ![изображение](https://private-user-images.githubusercontent.com/24588349/378573390-9689ba57-57ae-4301-9bd3-816331ad67b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1NzYyMjMsIm5iZiI6MTcyOTU3NTkyMywicGF0aCI6Ii8yNDU4ODM0OS8zNzg1NzMzOTAtOTY4OWJhNTctNTdhZS00MzAxLTliZDMtODE2MzMxYWQ2N2I3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDA1NDUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhYzRiYmRkMmY4NTRiNjk0NGMwMDNmNWRlZjk4ZWM1OWQyNTBiNTgxN2Y4YmFjMGZmMTc5NGYyYTBhOGJkYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8JDm2e_ksIPQoBHO5yABqkNw_1uFKmNaLtbXdvDNTTE)
> 
> После удаления исходного файла .config и восстановления файла по умолчанию вам необходимо открыть файл Grasshopper Application.exe.config с помощью блокнота и изменить в нем версию Rhino на 8: ![изображение](https://private-user-images.githubusercontent.com/24588349/378573865-cf67ba2b-e3d1-4ab7-b8ef-9bffce66a254.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1NzYyMjMsIm5iZiI6MTcyOTU3NTkyMywicGF0aCI6Ii8yNDU4ODM0OS8zNzg1NzM4NjUtY2Y2N2JhMmItZTNkMS00YWI3LWI4ZWYtOWJmZmNlNjZhMjU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDA1NDUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzNTc0MThmZTQ5ZTE5YTczYjhkMTIwMmNhNmIzMTRkMzM2Y2Q5NzUyMzEwYzI0OGVmYzc4MDMyZjE4MGQ5NzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gTwdeCQiqkHVLKFrte5I0iKGoxX9_GRnNuCqB-jfb1E)
> 
> Я выпущу новую версию в конце недели.

Hi. Thanks, I tried to do it according to the instructions. But I have Tekla 2022. And in the folder C:\TeklaStructures\2022.0\Environments\common\extensions\GrasshopperApplication there is no .bak file
![image_2024-10-22_09-53-09](https://github.com/user-attachments/assets/2b8cb6cd-b879-49d7-acd5-19b4d0a7c904)

I tried to enter the lines in the file
<userSettings>
<DrawingLink.UI.Properties.Settings>
<setting name="RhinoVersion" serializeAs="String">
<value>8</value>
</setting>
</DrawingLink.UI.Properties.Settings>
</userSettings>
![image_2024-10-22_09-53-09 (2)](https://github.com/user-attachments/assets/162f9e72-cc30-4a5b-b0e9-aed1b3fd4dfa)

But after adding these lines, the gx plugin does not open at all. It does not even say that it is trying to launch Rhino 7. I tried to restart the computer, but it did not help.

**Comment by olszewski-grzegorz** [comment]
@Karbofo7, I have just released new version of Grasshopper Application -> [1.2](https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/releases/tag/GA_1.2)

Once again, sorry for the inconvenience. Please try the fixed version.

**Comment by Karbofo7** [comment]
> @Karbofo7, I have just released new version of Grasshopper Application -> [1.2](https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/releases/tag/GA_1.2)
> 
> Once again, sorry for the inconvenience. Please try the fixed version.

Thank you, now the app works with Rhino 8!
