### ISSUE TITLE
Pattern lines in the Tekla

### ISSUE THREAD

**Issue by Karbofo7** [LetsConstructIT/Grasshopper-TeklaDrawingLink#57]
Hello! 
Tell me please: do you plan to add a "Pattern Line" component in the future? I tried to use the "Line" component, but I can only create a normal line. I can't create a Pattern Line using the Line component(
You make a very useful program, thank you!

**Comment by olszewski-grzegorz** [comment]
Brilliant idea! I really like it, sounds very useful.
Pattern Line is a specific sort of Tekla component. You could try to insert it with existing drawing Plugin / Plugin Input components, but in my opinion they deserve separate component.

It will be added in the next version of Drawing Link.

**Comment by Karbofo7** [comment]
![image_2024-10-29_11-16-08](https://github.com/user-attachments/assets/afdfdaad-8a4f-483f-b9e1-0b527945711d)
Thank you! I was able to create a Pattern Line via the Plugin. But for some reason it works slowly. The most important thing is that it works, thank you!
