### ISSUE TITLE
View Properties Display CS

### ISSUE THREAD

**Issue by ArthurKo33** [LetsConstructIT/Grasshopper-TeklaDrawingLink#70]
Hi Greg.

I am trying to make assembly Dimensionig with drawing link.
I found Something odd, i did algoritm for dimensioning when my model Work plane is default one.
But if i apply my algoritm when my Work Plane in the model is not default. The CS in the drawings is not correct and dim lines is out of the assembly.

This is how it look when work plane is in default Position.
![image](https://github.com/user-attachments/assets/202a71f3-acff-4652-a389-0c844122006f)

This are dimensions when Work Plane manually Changed. 
![image](https://github.com/user-attachments/assets/dab8ece5-c47b-4fdb-9ec2-3899652e9f03)

**Comment by olszewski-grzegorz** [comment]
Hello @ArthurKo33 ,
it's not odd, rather standard in Tekla :)

When you are asking for geometry of Tekla objects, like get solid or beam handles, they are returned in the current work plane. It's how the Tekla Open API is working.

I see three solutions:
1) Do nothing, just say loudly in your work environment that before triggering the script, work plane has to be set as global.
2) New group of components to get current work plane and set new one.
3) Modify Simple Orient component to take into account this transformation.

What do you think about that? Which solution seems most logic for you?

**Comment by ArthurKo33** [comment]
Hi Greg.

For me option one is enough, now that i aware of this condition.
Just when it happened it took me some time before i realized the problem.
Maybe you should just add a note to the description.

And again I want to thank you for your work. Tekla drawing link was one of the main reason i started learnig grasshopper.
