### ISSUE TITLE
Grasshopper-TeklaDrawingLink for Tekla 20.0

### ISSUE THREAD

**Issue by THMO090323** [LetsConstructIT/Grasshopper-TeklaDrawingLink#73]
Hi Greg!
Please create the tool 'Grasshopper-Tekla Drawing Link' for Tekla 20.0, as I need to use it on this version. 
Please send it to me via email at: phamthuong080192@gmail.com
Thank you!

**Comment by olszewski-grzegorz** [comment]
Hello @THMO090323 ,
sorry but I will not compile Drawing Link for Tekla versions before 2019.
I don't have any possiblity to check how they are working. 

If you really need this, you can try to download the source code and compile it on your own in Visual Studio.
Sorry, but I will not do this for you.
