### ISSUE TITLE
Can't use some components

### ISSUE THREAD

**Issue by dandad36** [LetsConstructIT/Grasshopper-TeklaDrawingLink#9]
Hi, I hope this is the right place to post. I'm using Tekla 2021 and 2022 and I've encountered this issue for both versions. The same errors showed up for Arrow/ Font/ Mark/ Text Attributes. Other Attributes definitions work fine. Is this a known problem?
![image](https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/assets/41262390/9da2771d-0c61-4365-8b90-a142dbe564df)
![image](https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/assets/41262390/f8da7e7d-09d5-4bab-8c46-93689334391a)

**Comment by olszewski-grzegorz** [comment]
Hello, nice to see you :)
This is the right place to raise this kind of issue. You're right - there are missing definitions for specified attributes.
I will try to fix asap and release new version.

**Comment by olszewski-grzegorz** [comment]
@dandad36 please check the newest release 2.3.0 with hotfix:
[https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/releases/tag/2.3.0](url)

**Comment by dandad36** [comment]
Thank you for the quick solution. That seems to fix it :)
